apiVersion: v1
kind: Service
metadata:
  name: second-app-service
spec:
  selector:
    app: kub-second-app
  ports:
    - protocol: 'TCP'
      port: 8000
      targetPort: 8080
  type: LoadBalancer
